
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 20 15:46:57 PDT 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ASTConstants {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int STR = 29;
  public static final int NO_EXPR = 33;
  public static final int COND = 14;
  public static final int LPAREN = 11;
  public static final int INT = 28;
  public static final int FORMAL = 6;
  public static final int STR_CONST = 36;
  public static final int RPAREN = 12;
  public static final int NO_TYPE = 35;
  public static final int LT = 24;
  public static final int BLOCK = 17;
  public static final int OBJECT = 34;
  public static final int BOOL = 30;
  public static final int CLASS = 3;
  public static final int COMP = 27;
  public static final int TYPCASE = 16;
  public static final int LOOP = 15;
  public static final int PLUS = 19;
  public static final int ASSIGN = 8;
  public static final int ID = 38;
  public static final int EOF = 0;
  public static final int METHOD = 4;
  public static final int INT_CONST = 37;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 21;
  public static final int ISVOID = 32;
  public static final int EQ = 25;
  public static final int BRANCH = 7;
  public static final int ATTR = 5;
  public static final int COLON = 13;
  public static final int NEG = 23;
  public static final int DISPATCH = 10;
  public static final int LET = 18;
  public static final int LEQ = 26;
  public static final int STATIC_DISPATCH = 9;
  public static final int SUB = 20;
  public static final int LINENO = 39;
}

