
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 20 15:46:54 PDT 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class TokenConstants {
  /* terminals */
  public static final int MULT = 27;
  public static final int INHERITS = 7;
  public static final int POOL = 11;
  public static final int CASE = 14;
  public static final int LPAREN = 35;
  public static final int SEMI = 33;
  public static final int MINUS = 26;
  public static final int STR_CONST = 40;
  public static final int RPAREN = 36;
  public static final int NOT = 21;
  public static final int TYPEID = 43;
  public static final int LT = 29;
  public static final int IN = 6;
  public static final int COMMA = 32;
  public static final int CLASS = 2;
  public static final int FI = 4;
  public static final int DIV = 25;
  public static final int LOOP = 10;
  public static final int PLUS = 24;
  public static final int ASSIGN = 20;
  public static final int IF = 5;
  public static final int DOT = 30;
  public static final int LE = 22;
  public static final int OF = 16;
  public static final int EOF = 0;
  public static final int INT_CONST = 41;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int ISVOID = 19;
  public static final int EQ = 28;
  public static final int ERROR = 23;
  public static final int COLON = 34;
  public static final int NEG = 31;
  public static final int LBRACE = 38;
  public static final int ELSE = 3;
  public static final int DARROW = 17;
  public static final int WHILE = 13;
  public static final int ESAC = 15;
  public static final int LET = 8;
  public static final int RBRACE = 39;
  public static final int LET_STMT = 9;
  public static final int THEN = 12;
  public static final int BOOL_CONST = 42;
  public static final int OBJECTID = 44;
  public static final int AT = 37;
}

